language: python
cache:
   directories:
       - $HOME/.cache/pip
python:
 - "3.5"
before_install:
 - pip install nose coverage python-coveralls
install:
 - pip install .
 - python -m adeft.download
script:
 - nosetests adeft -v --with-coverage --cover-inclusive --cover-package=adeft
after_success:
 - coveralls
